### ISSUE TITLE
附加武器伞形发射角度可能有问题

### ISSUE THREAD

**Issue by ZachPLin** [ChrisLv-CN/DPKratos-Lite#1]
DIY论坛好像挂了，所以就发在这吧。使用的是0.15和0.16。

我想做个跟战舰世界类似的鱼雷发射器，以下设置可以比较完美实现伞形发射的直线鱼雷，但必须使用AttachFire.RadialAngle=180。如果我设置其他角度会从船的侧身发射出去，而不是向前发射。比如说30，则是向后朝右30°发射。扇形的宽度也确实是会根据设置数值变小。我觉得这是个bug。也有可能是Speed=15 的bug，高于15鱼雷就是普通的导弹弹道了。

![TorpFire30](https://user-images.githubusercontent.com/94885915/199380169-41d1c47c-41d7-4e47-8dd5-7c5022c275af.JPG)

另一个可能不是bug，以下图片为AttachFire.RadialAngle=180。 向北发射会有完美伞形，向南的话，中间的几个鱼雷就会打偏。

![TorpFireNorth](https://user-images.githubusercontent.com/94885915/199380182-0a03b40b-e141-4e14-bd9b-251b4140859d.JPG)

![TorpFireSouth](https://user-images.githubusercontent.com/94885915/199380189-d82c232f-0559-491c-aa55-ad79dff22d1c.JPG)

如果大佬有更好的做直线散射鱼雷的方法，也请多指教了。

[SUB]
...
ExtraFire.Primary=MoreTorpedo

[MoreTorpedo]
Damage=50
ROF=240
Range=7
Projectile=StraightTorpedo
Speed=15 ；大于15会变成导弹
Report=SubAttack
Warhead=APSplash
DecloakToFire=no
Burst=6
AttachFire.UseROF=yes ;启用则每个附加武器独立计算ROF，ROF受AE加成影响
AttachFire.CheckRange=yes ;启用每个附加武器检查射程
AttachFire.RadialFire=yes ;按照Burst伞形发射，仅影响ROT类型
**AttachFire.RadialAngle=180 ;按照Burst伞形发射，分割的角度**
AttachFire.SimulateBurst=no 
AttachFire.OnlyFireInTransport=no ;只有在载具内才能使用这个附加武器
AttachFire.UseAlternateFLH=no ;在载具内时，不使用AttachFire指定的FLH而是启用载具对应的FLH
AttachFire.Feedback=no ;攻击武器发射者
ProximityRange=1.0  ;提前引爆距离，单位格

[StraightTorpedo]
Arm=128
Shadow=no
Ranged=yes
Image=SUBT
ROT=3 
AA=no
AG=yes
Proximity=yes
Proximity.Penetration=yes ;启用碰撞引信时，检测到碰撞是否穿透，yes时，启用下面的设置
Proximity.PenetrationTimes=1 ;引爆多少次后销毁
Proximity.PenetrationBuildingOnce=yes ;每个格子检测一次，建筑多格会收到多次伤害，yes时，只穿透一次
Proximity.Force=yes ;强制启用碰撞引信
Proximity.Blade=yes ;检测无视高度，所有处于格子位置上的单位都视为判定目标
Proximity.Arm=128 ;检测的距离，球型半径，单位Lepton，一格是256
Proximity.AffectsOwner=yes ;碰触发射者同阵营单位
Proximity.AffectsAllies=no ;碰触友军
Proximity.AffectsEnemies=yes ;碰触敌人
Proximity.AffectsClocked=yes ;碰触隐形的单位
DestroySelf.Delay=70 ;延迟多长时间自毁，可以写yes=0，no=不起做用，自毁AE等同并覆盖单位身上的DestroySelf.Delay
DestroySelf.Peaceful=no ;平静的消失，不发生爆炸

**Comment by ChrisLv-CN** [comment]
修好了，更新到0.18
