### ISSUE TITLE
安装使用后游戏帧率降低

### ISSUE THREAD

**Issue by kotoricon** [ChrisLv-CN/DPKratos-Lite#2]
同样的调用cpu多核后ares+phobos+cncddraw的情况下可以做到遭遇战开局头5分钟100-200fps，再往后可能会降到20-40左右但是如果自己弄一个全图清屏之类的东西可以重新恢复80-120fps
但是同样的配置下加上DP后开局短时间不到一分钟就发现从120-100-80-60-40-30不停往下掉帧直到掉到一直只有20fps左右，再以同样的方式进行全图清理也无效一直保持只能20-30左右感觉游戏卡的不行

是否有相关的配置需要设置还是本身有什么问题？

**Comment by ChrisLv-CN** [comment]
本身有问题
